[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/whoop-token"
  to = "/.netlify/functions/whoop-token"
  status = 200

[[redirects]]
  from = "/api/whoop-api/*"
  to = "/.netlify/functions/whoop-api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
